# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloudrun_django_cloudmigrate_yaml_python]
steps:
  - id: "Build Container Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "-f", "app/Dockerfile.cloud", "."]

  - id: "Push Container Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]

  - id: "Migrate database"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run jobs delete migrate-job --region ${_REGION} --quiet || true
        gcloud run jobs create migrate-job \
          --region ${_REGION} \
          --image ${_IMAGE_NAME} \
          --service-account ${_SERVICE_ACCOUNT} \
          --set-cloudsql-instances ${_CLOUD_SQL_CONNECTION_NAME} \
          --set-secrets APPLICATION_SETTINGS=${_SECRET_SETTINGS_NAME}:latest \
          --set-env-vars DJANGO_SETTINGS_MODULE=config.settings.cloud \
          --command python,manage.py,migrate,--noinput \
          --execute-now

  - id: "Create superuser"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run jobs delete superuser-job --region ${_REGION} --quiet || true
        gcloud run jobs create superuser-job \
          --region ${_REGION} \
          --image ${_IMAGE_NAME} \
          --set-cloudsql-instances ${_CLOUD_SQL_CONNECTION_NAME} \
          --set-secrets APPLICATION_SETTINGS=${_SECRET_SETTINGS_NAME}:latest \
          --service-account ${_SERVICE_ACCOUNT} \
          --set-env-vars DJANGO_SETTINGS_MODULE=config.settings.cloud \
          --set-env-vars DJANGO_SUPERUSER_USERNAME=${_ADMIN_USERNAME} \
          --set-env-vars DJANGO_SUPERUSER_EMAIL=${_ADMIN_EMAIL} \
          --set-secrets DJANGO_SUPERUSER_PASSWORD=${_ADMIN_PASSWORD_NAME}:latest \
          --command python,manage.py,createsuperuser,--noinput \
          --execute-now

  - id: "Load test data"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run jobs delete loaddata-job --region ${_REGION} --quiet || true
        gcloud run jobs create loaddata-job \
          --region ${_REGION} \
          --image ${_IMAGE_NAME} \
          --set-cloudsql-instances ${_CLOUD_SQL_CONNECTION_NAME} \
          --set-secrets APPLICATION_SETTINGS=${_SECRET_SETTINGS_NAME}:latest \
          --service-account ${_SERVICE_ACCOUNT} \
          --set-env-vars DJANGO_SETTINGS_MODULE=config.settings.cloud \
          --command python,manage.py,loaddata,test_comic_data \
          --execute-now

  # - id: "Deploy to Cloud Run"
  #   name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: /bin/bash
  #   args:
  #     - "-c"
  #     - |
  #       gcloud run deploy ${_SERVICE_NAME} \
  #         --region ${_REGION} \
  #         --image ${_IMAGE_NAME} \
  #         --add-cloudsql-instances ${_CLOUD_SQL_CONNECTION_NAME} \
  #         --set-secrets APPLICATION_SETTINGS=${_SECRET_SETTINGS_NAME}:latest \
  #         --set-env-vars DJANGO_SETTINGS_MODULE=config.settings.cloud \
  #         --set-env-vars PORT=8080 \
  #         --service-account ${_SERVICE_ACCOUNT} \
  #         --timeout 300 \
  #         --allow-unauthenticated

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _INSTANCE_NAME: comic-instance
  _CLOUD_SQL_CONNECTION_NAME: ${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}
  _REGION: us-central1
  _SERVICE_NAME: comicchase-service
  _SERVICE_ACCOUNT: cloudrun-serviceaccount@${PROJECT_ID}.iam.gserviceaccount.com
  _SECRET_SETTINGS_NAME: application_settings
  _ARTIFACT_REGISTRY: cloud-run-source-deploy
  _IMAGE_NAME: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}
  _ADMIN_USERNAME: admin
  _ADMIN_EMAIL: admin@example.com
  _ADMIN_PASSWORD_NAME: superuser_password

images:
  - "${_IMAGE_NAME}"
# [END cloudrun_django_cloudmigrate_yaml_python]
