# Generated by Django 5.2.8 on 2025-12-29 18:56

from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_alter_series_options_alter_series_author_jp_and_more'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),

        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': '使用者追蹤漫畫列表', 'verbose_name_plural': '使用者追蹤漫畫列表'},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'series'), name='unique_subscription'),
        ),
    ]
