# Generated by Django 5.2.8 on 2026-02-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='此訂閱最後一次成功發送通知的時間', null=True),
        ),
    ]
