# Generated by Django 5.2.8 on 2026-02-17 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0008_volume_created_at'),
        ('subscriptions', '0002_alter_subscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='comic.volume')),
            ],
            options={
                'verbose_name': '通知紀錄',
                'verbose_name_plural': '通知紀錄',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'volume'), name='unique_notification_per_user_volume')],
            },
        ),
    ]
