# Generated by Django 5.2.8 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_notified_at',
            field=models.DateTimeField(
                blank=True,
                help_text='最後一次發送新書通知的時間',
                null=True,
            ),
        ),
    ]
