# Generated by Django 5.2.8 on 2026-02-02 15:19

import uuid

from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    """為每個現有用戶生成唯一的取消訂閱 token"""
    CustomUser = apps.get_model("accounts", "CustomUser")
    for user in CustomUser.objects.all():
        user.unsubscribe_token = uuid.uuid4()
        user.save(update_fields=["unsubscribe_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # 步驟 1: 先添加可為空的欄位（不含唯一約束）
        migrations.AddField(
            model_name="customuser",
            name="unsubscribe_token",
            field=models.UUIDField(
                null=True,
                editable=False,
                help_text="用於電子郵件取消訂閱的唯一識別碼",
            ),
        ),
        # 步驟 2: 為現有用戶生成唯一的 token
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        # 步驟 3: 設定預設值、非空約束和唯一約束
        migrations.AlterField(
            model_name="customuser",
            name="unsubscribe_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                help_text="用於電子郵件取消訂閱的唯一識別碼",
            ),
        ),
    ]
