# Generated by manually (perfect solution implementation)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_unsubscribe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="receive_email",
            field=models.BooleanField(
                default=True,
                help_text="接收每週新書通知",
                verbose_name="接收郵件通知",
            ),
        ),
    ]
