# Generated by Django 5.2.8 on 2025-11-14 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="出版社名稱"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("JP", "Japan"), ("TW", "Taiwan")],
                        help_text="JP (日本) 或 TW (台灣)",
                        max_length=2,
                        verbose_name="地區",
                    ),
                ),
            ],
            options={
                "verbose_name": "出版社",
                "verbose_name_plural": "出版社",
            },
        ),
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_jp",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="日文原名",
                    ),
                ),
                (
                    "title_tw",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="台灣譯名",
                    ),
                ),
                (
                    "author_jp",
                    models.CharField(max_length=100, verbose_name="日文原名作者"),
                ),
                (
                    "author_tw",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="台灣譯名作者",
                    ),
                ),
                (
                    "status_jp",
                    models.CharField(
                        choices=[
                            ("ongoing", "連載中"),
                            ("completed", "已完結"),
                            ("hiatus", "休刊中"),
                        ],
                        default="ongoing",
                        max_length=10,
                        verbose_name="日本出版狀態",
                    ),
                ),
                (
                    "publisher_jp",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"region": "JP"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_comics",
                        to="comic.publisher",
                        verbose_name="日本連載出版社",
                    ),
                ),
            ],
            options={
                "verbose_name": "漫畫作品",
                "verbose_name_plural": "漫畫作品",
                "ordering": ["title_tw", "title_jp"],
            },
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume_number", models.PositiveIntegerField(verbose_name="卷數")),
                (
                    "release_date_jp",
                    models.DateField(
                        blank=True, null=True, verbose_name="日本發售日期"
                    ),
                ),
                (
                    "isbn_jp",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="日本 ISBN"
                    ),
                ),
                (
                    "release_date_tw",
                    models.DateField(
                        blank=True, null=True, verbose_name="台灣發售日期"
                    ),
                ),
                (
                    "isbn_tw",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="台灣 ISBN"
                    ),
                ),
                (
                    "comic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="comic.comic",
                        verbose_name="關聯漫畫",
                    ),
                ),
                (
                    "publisher_jp",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"region": "JP"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jp_volumes",
                        to="comic.publisher",
                        verbose_name="日本出版社",
                    ),
                ),
                (
                    "publisher_tw",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"region": "TW"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tw_volumes",
                        to="comic.publisher",
                        verbose_name="台灣代理出版社",
                    ),
                ),
            ],
            options={
                "verbose_name": "單行本",
                "verbose_name_plural": "單行本",
                "ordering": ["comic", "volume_number"],
                "unique_together": {("comic", "volume_number")},
            },
        ),
    ]
