# Generated by Django 5.2.8 on 2025-11-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comic", "0002_remove_comic_publisher_jp_alter_volume_comic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_jp",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="日文原名",
                    ),
                ),
                (
                    "title_tw",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="台灣譯名",
                    ),
                ),
                (
                    "author_jp",
                    models.CharField(max_length=100, verbose_name="日文原名作者"),
                ),
                (
                    "author_tw",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="台灣譯名作者",
                    ),
                ),
                (
                    "status_jp",
                    models.CharField(
                        choices=[
                            ("ongoing", "連載中"),
                            ("completed", "已完結"),
                            ("hiatus", "休刊中"),
                        ],
                        default="ongoing",
                        max_length=10,
                        verbose_name="日本出版狀態",
                    ),
                ),
                (
                    "latest_volume_number_jp",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="最新卷數 (日)"
                    ),
                ),
                (
                    "latest_release_date_jp",
                    models.DateField(
                        blank=True, null=True, verbose_name="最新發售日 (日)"
                    ),
                ),
                (
                    "latest_volume_number_tw",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="最新卷數 (台)"
                    ),
                ),
                (
                    "latest_release_date_tw",
                    models.DateField(
                        blank=True, null=True, verbose_name="最新發售日 (台)"
                    ),
                ),
            ],
            options={
                "verbose_name": "系列漫畫",
                "verbose_name_plural": "系列漫畫",
                "ordering": ["title_tw", "title_jp"],
            },
        ),
        migrations.AlterModelOptions(
            name="volume",
            options={
                "ordering": ["series", "volume_number", "region", "release_date"],
                "verbose_name": "單行本",
                "verbose_name_plural": "單行本",
            },
        ),
        migrations.RemoveIndex(
            model_name="volume",
            name="comic_volum_isbn_tw_885c89_idx",
        ),
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="volume",
            name="isbn",
            field=models.CharField(
                blank=True, max_length=13, null=True, unique=True, verbose_name="ISBN"
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_volumes",
                to="comic.publisher",
                verbose_name="出版社",
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="region",
            field=models.CharField(
                choices=[("JP", "Japan"), ("TW", "Taiwan")],
                db_index=True,
                default="JP",
                max_length=2,
                verbose_name="地區",
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="release_date",
            field=models.DateField(blank=True, null=True, verbose_name="發售日期"),
        ),
        migrations.AddField(
            model_name="volume",
            name="variant",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如：特裝版、首刷限定。普通版請留空。",
                max_length=50,
                verbose_name="版本備註",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="region",
            field=models.CharField(
                choices=[("JP", "Japan"), ("TW", "Taiwan")],
                default="JP",
                help_text="JP (日本) 或 TW (台灣)",
                max_length=2,
                verbose_name="地區",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="volume_number",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="卷數"
            ),
        ),
        migrations.AddField(
            model_name="volume",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volumes",
                to="comic.series",
                verbose_name="關聯漫畫",
            ),
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.UniqueConstraint(
                fields=("series", "volume_number", "region", "variant"),
                name="unique_volume_variant",
            ),
        ),
        migrations.RemoveField(
            model_name="volume",
            name="comic",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="isbn_jp",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="isbn_tw",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="publisher_jp",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="publisher_tw",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="release_date_jp",
        ),
        migrations.RemoveField(
            model_name="volume",
            name="release_date_tw",
        ),
        migrations.DeleteModel(
            name="Comic",
        ),
    ]
