# Generated by Django 5.2.8 on 2025-11-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comic", "0003_series_alter_volume_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="series",
            name="latest_release_date_jp",
        ),
        migrations.RemoveField(
            model_name="series",
            name="latest_release_date_tw",
        ),
        migrations.RemoveField(
            model_name="series",
            name="latest_volume_number_jp",
        ),
        migrations.RemoveField(
            model_name="series",
            name="latest_volume_number_tw",
        ),
        migrations.AddField(
            model_name="series",
            name="latest_volume_jp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_latest_jp",
                to="comic.volume",
                verbose_name="最新單行本 (日)",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="latest_volume_tw",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_latest_tw",
                to="comic.volume",
                verbose_name="最新單行本 (台)",
            ),
        ),
    ]
