# Generated by Django 5.2.8 on 2025-12-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_remove_series_latest_release_date_jp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['title_tw', 'title_jp'], 'verbose_name': '系列', 'verbose_name_plural': '系列'},
        ),
        migrations.AlterField(
            model_name='series',
            name='author_jp',
            field=models.CharField(max_length=100, verbose_name='作者原名'),
        ),
        migrations.AlterField(
            model_name='series',
            name='author_tw',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='作者譯名'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title_jp',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='原名'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title_tw',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='譯名'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='comic.series', verbose_name='系列'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='variant',
            field=models.CharField(blank=True, default='', help_text='如：特裝版、首刷限定。普通版留空。', max_length=50, verbose_name='版本備註'),
        ),
    ]
