# Generated by Django 5.2.8 on 2025-12-06 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comic", "0004_remove_series_latest_release_date_jp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="first_published_year",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="漫畫首次出版的年份",
                null=True,
                verbose_name="首次出版年份",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="genres",
            field=models.CharField(
                blank=True,
                help_text="多個類型用逗號分隔，例如：action,adventure,fantasy",
                max_length=255,
                verbose_name="類型",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="author_jp",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="作者原名"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="author_tw",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="作者譯名"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="status_jp",
            field=models.CharField(
                choices=[
                    ("ongoing", "連載中"),
                    ("completed", "已完結"),
                    ("hiatus", "休刊中"),
                ],
                db_index=True,
                default="ongoing",
                max_length=10,
                verbose_name="日本出版狀態",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="title_jp",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="原名"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="title_tw",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="譯名",
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="variant",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如：特裝版、首刷限定。普通版留空。",
                max_length=50,
                verbose_name="版本備註",
            ),
        ),
        migrations.CreateModel(
            name="UserCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏時間"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collected_by",
                        to="comic.series",
                        verbose_name="漫畫系列",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用者收藏",
                "verbose_name_plural": "使用者收藏",
                "ordering": ["-created_at"],
                "unique_together": {("user", "series")},
            },
        ),
    ]
