# Generated by Django 5.2.8 on 2025-12-29 18:01

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_alter_series_options_alter_series_author_jp_and_more'),
    ]

    operations = [
        TrigramExtension(),

        migrations.AddIndex(
            model_name='series',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_tw'], name='series_title_tw_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='series',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_jp'], name='series_title_jp_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
