# Generated by Django 5.2.8 on 2025-12-29 18:01

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_alter_series_options_alter_series_author_jp_and_more'),
    ]

    operations = [
        TrigramExtension(),

        migrations.AddIndex(
            model_name='series',
            index=GinIndex(fields=['title_tw'], name='series_title_tw_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='series',
            index=GinIndex(fields=['title_jp'], name='series_title_jp_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='series',
            index=GinIndex(fields=['author_tw'], name='series_author_tw_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='series',
            index=GinIndex(fields=['author_jp'], name='series_author_jp_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
