# Generated by Django 5.2.8 on 2026-01-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_alter_series_options_alter_series_author_jp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['series', 'region', 'volume_number', 'release_date'], 'verbose_name': '單行本', 'verbose_name_plural': '單行本'},
        ),
        migrations.AddField(
            model_name='volume',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='封面圖片 URL'),
        ),
    ]
