# Generated by Django 5.2.8 on 2026-01-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0006_alter_volume_options_volume_image_url'),
        ('comic', '0006_series_series_title_tw_trgm_idx_and_more'),
    ]

    operations = [
    ]
