# Generated by Django 5.2.8 on 2026-02-17 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0007_merge_20260115_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='此筆資料寫入資料庫的時間', verbose_name='入庫時間'),
            preserve_default=False,
        ),
    ]
