# Generated by Django 5.2.8 on 2025-11-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='publisher_jp',
        ),
        migrations.AlterField(
            model_name='volume',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='comic.comic', verbose_name='關聯漫畫'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='isbn_tw',
            field=models.CharField(max_length=13, null=True, verbose_name='台灣 ISBN'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='卷數'),
        ),
        migrations.AddIndex(
            model_name='volume',
            index=models.Index(fields=['isbn_tw'], name='comic_volum_isbn_tw_885c89_idx'),
        ),
    ]
