# Generated by Django 5.2.8 on 2025-11-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_remove_comic_publisher_jp_alter_volume_comic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeJp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_jp', models.CharField(max_length=13, null=True, unique=True, verbose_name='日本 ISBN')),
                ('title_jp', models.CharField(blank=True, max_length=255, null=True, verbose_name='日文原名')),
                ('volume_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='卷數')),
                ('release_date_jp', models.DateField(blank=True, null=True, verbose_name='日本發售日期')),
            ],
            options={
                'verbose_name': '日版單行本',
                'verbose_name_plural': '日版單行本',
                'ordering': ['comic', 'volume_number'],
            },
        ),
        migrations.CreateModel(
            name='VolumeTw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_tw', models.CharField(max_length=13, null=True, unique=True, verbose_name='台灣 ISBN')),
                ('title_tw', models.CharField(blank=True, max_length=255, null=True, verbose_name='台灣譯名')),
                ('volume_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='卷數')),
                ('release_date_tw', models.DateField(blank=True, null=True, verbose_name='台灣發售日期')),
            ],
            options={
                'verbose_name': '台版單行本',
                'verbose_name_plural': '台版單行本',
                'ordering': ['comic', 'volume_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='volume',
            name='comic_volum_isbn_tw_885c89_idx',
        ),
        migrations.AlterField(
            model_name='volume',
            name='isbn_jp',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='日本 ISBN'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='isbn_tw',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='台灣 ISBN'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='卷數'),
        ),
        migrations.AddField(
            model_name='volumejp',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes_jp', to='comic.comic', verbose_name='所屬系列'),
        ),
        migrations.AddField(
            model_name='volumejp',
            name='publisher_jp',
            field=models.ForeignKey(blank=True, limit_choices_to={'region': 'JP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes_jp', to='comic.publisher', verbose_name='日本出版社'),
        ),
        migrations.AddField(
            model_name='volumetw',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes_tw', to='comic.comic', verbose_name='所屬系列'),
        ),
        migrations.AddField(
            model_name='volumetw',
            name='publisher_tw',
            field=models.ForeignKey(blank=True, limit_choices_to={'region': 'TW'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes_tw', to='comic.publisher', verbose_name='台灣代理出版社'),
        ),
        migrations.AddIndex(
            model_name='volumejp',
            index=models.Index(fields=['comic', 'volume_number'], name='comic_volum_comic_i_0871ec_idx'),
        ),
        migrations.AddIndex(
            model_name='volumetw',
            index=models.Index(fields=['comic', 'volume_number'], name='comic_volum_comic_i_6aac30_idx'),
        ),
    ]
