
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code/app

RUN pip install --upgrade pip
COPY ./app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/src ./

RUN chmod +x entrypoint.prod.sh wait-for-it.sh

ENTRYPOINT [ "/code/app/entrypoint.prod.sh" ]

CMD ["gunicorn", "--config", "/code/app/config/gunicorn/gunicorn_config.py"]
