
FROM python:3.12-slim

ARG USER_ID=1000
ARG GID=1000

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code/app

# Create non-root user
RUN groupadd -g $GID docker-users && \
    useradd -m --no-log-init -s /bin/bash -u $USER_ID -g $GID docker && \
    echo "docker:docker" | chpasswd && \
    adduser docker sudo

RUN pip install --upgrade pip
COPY ./app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/src ./

RUN chmod +x entrypoint.vm.sh wait-for-it.sh

# Copy supervisord config
RUN cp supervisord.conf /etc/supervisord.conf

# Create staticfiles directory and set ownership
RUN mkdir -p /code/app/staticfiles && \
    chown -R docker:docker-users /code/app

USER docker

ENTRYPOINT [ "/code/app/entrypoint.vm.sh" ]

# Use supervisord to manage processes (pip installed version is in /usr/local/bin)
CMD ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
